#include <gen_x64.h>
#include <reg.h>
#include <symbol.h>
#include <stdlib.h>


FILE* g_outfile = NULL;

static void cc_prologue(void) {
  fputs(
      ";; Generated by the BetterC compiler.\n"
      ";; Copyright (c) 2022 Ian Marco Moffett, The Qnixx team\n"
      ";; Licensed under the BSD 3-Clause\n"
      ";; See LICENSE at https://git.mkall.org/svr/BetterC.git/tree\n\n"
      "bits 64\n\n",
  g_outfile);
}


static void cc_func_prologue(size_t glob_sym_id) {
  fprintf(g_outfile, "$%s:\n"
                     "\tpush rbp\n"
                     "\tmov rbp, rsp\n", g_symtbl[glob_sym_id].name);
}


reg_t cc_x64_gen(astnode_t* node) {
  reg_t leftreg, rightreg;

  switch (node->op) {
    case A_FUNC:
      cc_func_prologue(node->left->id);
      return -1;
  }

  if (node->left) {
    leftreg = cc_x64_gen(node->left);
  }

  if (node->right) {
    rightreg = cc_x64_gen(node->right);
  }

  switch (node->op) {
    case A_ADD:
      return reg_add(leftreg, rightreg);
    case A_SUB:
      return reg_sub(leftreg, rightreg);
    case A_MUL:
      return reg_mul(leftreg, rightreg);
    case A_DIV:
      return reg_div(leftreg, rightreg);
    case A_INTLIT:
      return reg_load(node->val_int);
    default:
      printf("__INTERNAL_ERRROR__: Invalid AST operator %d\n", node->op);
      exit(1);
  }

  return -1;
}


void cc_gen_x64_init(void) {
  g_outfile = fopen("/tmp/bcc-out.asm", "w");
  cc_prologue();
}
